// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_combinepuzzlenumbers = new UnifiedLeaderboard("Combinepuzzlenumbers",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-drQsLYCEAIQAQ"
#else
            "Combinepuzzlenumbers"
#endif
            );

        public static UnifiedLeaderboard Combinepuzzlenumbers
        {
            get { return s_combinepuzzlenumbers; }
        }

        private static readonly UnifiedLeaderboard s_combinenumber2048 = new UnifiedLeaderboard("Combinenumber2048",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-drQsLYCEAIQAg"
#else
            "Combinenumber2048"
#endif
            );

        public static UnifiedLeaderboard Combinenumber2048
        {
            get { return s_combinenumber2048; }
        }

        private static readonly UnifiedLeaderboard s_connect = new UnifiedLeaderboard("Connect",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-drQsLYCEAIQAw"
#else
            "Connect"
#endif
            );

        public static UnifiedLeaderboard Connect
        {
            get { return s_connect; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "Combinepuzzlenumbers", s_combinepuzzlenumbers },
            { "Combinenumber2048", s_combinenumber2048 },
            { "Connect", s_connect },
        };
    }
}
